name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Build Storybook
        run: npm run build-storybook
      - name: Copy Storybook
        run: rm -rf /var/www/html/ && cp -r storybook-static /var/www/html/
